/* Additional record code for Hello generated by the OpenModelica Compiler OpenModelica 1.13.0~dev-1098-g8f6610b. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

