/* Simulation code for Hello generated by the OpenModelica Compiler OpenModelica 1.13.0~dev-1098-g8f6610b. */
#if !defined(Hello__MODEL_H)
#define Hello__MODEL_H
#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "Hello_functions.h"


extern void Hello_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Hello_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Hello_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Hello_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Hello_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Hello_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Hello_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Hello_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Hello_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Hello_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Hello_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Hello_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Hello_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Hello_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Hello_relationDescription(int i);
extern void Hello_function_initSample(DATA *data, threadData_t *threadData);
extern int Hello_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int Hello_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int Hello_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int Hello_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int Hello_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int Hello_functionJacG_column(void* data, threadData_t *threadData);
extern int Hello_functionJacA_column(void* data, threadData_t *threadData);
extern int Hello_functionJacB_column(void* data, threadData_t *threadData);
extern int Hello_functionJacC_column(void* data, threadData_t *threadData);
extern int Hello_functionJacD_column(void* data, threadData_t *threadData);
extern const char* Hello_linear_model_frame(void);
extern const char* Hello_linear_model_datarecovery_frame(void);
extern int Hello_mayer(DATA* data, modelica_real** res, short *);
extern int Hello_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Hello_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Hello_setInputData(DATA *data, const modelica_boolean file);
extern int Hello_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Hello_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Hello_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int Hello_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void Hello_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Hello_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Hello_inputNames(DATA* data, char ** names);
extern int Hello_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Hello_functionLocalKnownVars(DATA*, threadData_t*);
extern int Hello_symbolicInlineSystem(DATA*, threadData_t*);

#include "Hello_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#endif

